# Generated by Django 3.1.7 on 2021-03-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='code',
            field=models.CharField(default=' ', max_length=15),
            preserve_default=False,
        ),
    ]
